export const START_REQUEST = 'START_REQUEST';
export const END_REQUEST = 'END_REQUEST';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const FINISH_FETCH_MOVIES = 'FINISH_FETCH_MOVIES';
export const FINISH_PLAY_MOVIE = 'FINISH_PLAY_MOVIE';
export const PLAY_MOVIE = 'PLAY_MOVIE';
